### ISSUE TITLE
Add number of races to Trail Circuit leaders pages

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#222] opened 2024-10-14 15:34 UTC
As someone who's curious about how a score was achieved, I'd be interested in seeing a column listing the number of races each runner completed in the various Leaders pages like this one for Stonehead.

https://trailcircuit.fingerlakesrunners.org/Overall/Points/F/

**Comment by SteveDesmond-ca** [comment] 2024-10-14 15:37
lol, good timing -- duplicate of #223

**Closed by SteveDesmond-ca** 2024-10-14 15:37 UTC
